name: build-nix
run-name: Nitro Enclaves Linux kernel build - Nix

on: [push, pull_request]

jobs:
  build_changes:
    name: build_changes
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: install nix
        uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a # v20
      - name: build artifacts
        run: nix-build --pure
