name: build-nix
run-name: Nitro Enclaves Linux kernel build - Nix

on: [push, pull_request]

jobs:
  build_changes:
    name: build_changes
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: install nix
        uses: cachix/install-nix-action@d1ca217b388ee87b2507a9a93bf01368bde7cec2 # v31.1.0
      - name: build artifacts
        run: nix-build --pure
