name: release
run-name: Nitro Enclaves Linux Kernel release

on:
  push:
    tags:
      - '**'

jobs:
  build_release:
    name: build_release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: install nix
        uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a # v20
      - name: build artifacts
        run: nix-build --pure
      - name: version
        run: grep 'version =' default.nix >> $GITHUB_ENV
        id: version
      - name: changelog
        run: |
          csplit -s CHANGELOG.md "/##/" {0}
          tail -n +3 xx01 > CHANGELOG.tmp
        id: changelog
      - name: release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        id: create_release
        with:
          draft: false
          prerelease: false
          tag_name: ${{ env.version }}
          body_path: CHANGELOG.tmp
          files: ./result/bzImage, ./result/nsm.ko
        env:
          GITHUB_TOKEN: ${{ github.token }}
